-- Create the 'vagas' table if it doesn't exist
create table if not exists public.vagas (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  company text not null,
  location text,
  description text,
  link text,
  type text default 'Remoto',
  salary text,
  posted_at text,
  source text default 'linkedin'
);

-- Set up Row Level Security (RLS)
alter table public.vagas enable row level security;

-- Create policy to allow public read access
create policy "Allow public read access"
  on public.vagas for select
  using ( true );

-- Create policy to allow authenticated users (like the scraper if using a service role, or admin) to insert/update
-- For simplicity in this setup, we will allow anon insert if using the anon key (NOT RECOMMENDED for production, but easiest for local script testing without service role setup)
-- OR better: The script should use the service_role key if available, or we just allow anon inserts for now and user can restrict later.
-- Let's stick to a standard policy:
create policy "Enable insert for authenticated users only"
  on public.vagas for insert
  with check ( auth.role() = 'authenticated' ); 
  -- Note: The local script might need to sign in or use a service key.
  -- Alternatively, for this specific request, I will allow public insert temporarily or assume the user runs SQL in dashboard.
  
-- To keep it simple for the user's local script:
create policy "Allow public insert for testing"
  on public.vagas for insert
  with check ( true ); 
