-- ==========================================
-- FINAL MIGRATION: HERMENEUTA DB COMPLETO + SEED REAL V. RIBEIRA DATA
-- ==========================================

-- 1. ESTRUTURA (Garantir que todas existam)

CREATE TABLE IF NOT EXISTS config (
  key TEXT PRIMARY KEY,
  value JSONB,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT DEFAULT 'Geral',
  content TEXT NOT NULL,
  excerpt TEXT,
  author TEXT,
  author_id TEXT,
  image TEXT,
  date TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS eventos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  location TEXT,
  description TEXT,
  type TEXT DEFAULT 'PRESENCIAL',
  link TEXT,
  image TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS editors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT,
  bio TEXT,
  avatar TEXT,
  username TEXT UNIQUE,
  password TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS leituras (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT,
  type TEXT DEFAULT 'LIVRO',
  category TEXT,
  synopsis TEXT,
  cover TEXT,
  link TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS concursos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entidade TEXT NOT NULL,
  cargo TEXT NOT NULL,
  vagas TEXT,
  remuneracao TEXT,
  status TEXT DEFAULT 'Inscrições Abertas',
  nivel TEXT DEFAULT 'MUNICIPAL',
  link TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comarca TEXT,
  setor TEXT,
  telefone TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS instituicoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    city TEXT,
    address TEXT,
    phone TEXT,
    link TEXT,
    cover TEXT,
    type TEXT,
    description TEXT,
    history TEXT,
    presidents JSONB,
    services JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS equipamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT,
    description TEXT,
    price TEXT,
    link TEXT,
    image TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_id TEXT,
    user_id TEXT,
    user_name TEXT,
    user_avatar TEXT,
    user_email TEXT,
    text TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS voz_do_vale (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT,
    type TEXT,
    institution TEXT,
    year TEXT,
    resume TEXT,
    content TEXT,
    image TEXT,
    link TEXT,
    "isFeatured" BOOLEAN DEFAULT false,
    tags JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS reservas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT,
    location TEXT,
    description TEXT,
    image TEXT,
    link TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS vagas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    company TEXT,
    location TEXT,
    description TEXT,
    link TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. AJUSTES (Colunas extras)
ALTER TABLE news ADD COLUMN IF NOT EXISTS excerpt TEXT;
ALTER TABLE concursos ADD COLUMN IF NOT EXISTS link TEXT;
ALTER TABLE voz_do_vale ADD COLUMN IF NOT EXISTS tags JSONB;

-- 3. POVOAMENTO (Seeding)

INSERT INTO config (key, value) VALUES ('maintenance_mode', 'false') ON CONFLICT (key) DO NOTHING;

-- News ORIGINAIS (do mockNews.js)
INSERT INTO news (title, category, content, excerpt, author, author_id, image, date) VALUES
('Direitos do Boia-Fria: Como Garantir o Vínculo Empregatício', 'RURAL', 'O trabalhador rural temporário...', 'No Vale do Ribeira, o trabalho volante é realidade...', 'Dr. Hermeneuta', 'admin', 'https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&q=80&w=800', '19 Jan 2026'),
('Segurado Especial: Documentos Essenciais para Aposentadoria Rural', 'PREVIDENCIÁRIO', 'A aposentadoria rural por idade...', 'Notas de produtor, ITR e declarações de sindicatos...', 'Redação Hermeneuta', 'admin', 'https://images.unsplash.com/photo-1533230678604-5856b328a649?auto=format&fit=crop&q=80&w=800', '19 Jan 2026'),
('Fraudes Bancárias via PIX: Responsabilidade das Instituições', 'CONSUMIDOR', 'Com a popularização do PIX...', 'Bancos no Vale do Ribeira têm sido alvo de reclamações...', 'Equipe Jurídica', 'admin', 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=800', '18 Jan 2026'),
('Regularização de Pequenas Propriedades e APP no Vale', 'AMBIENTAL', 'O Vale do Ribeira é um santuário...', 'Viver em harmonia com a naturezea exige conhecer as regras...', 'Dr. Roberto Silva', 'admin', 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800', '17 Jan 2026'),
('Inventário Extrajudicial: Rapidez e Menos Custos em 2026', 'FAMÍLIA', 'A perda de um ente querido...', 'Saiba como a via administrativa em cartório resolve partilhas...', 'Dra. Helena Martins', 'admin', 'https://images.unsplash.com/photo-1589216532372-1c2a367900d9?auto=format&fit=crop&q=80&w=800', '16 Jan 2026')
ON CONFLICT DO NOTHING;

-- Reservas (RESTAURANTES, HOTÉIS e TURISMO no Vale do Ribeira)
INSERT INTO reservas (title, category, location, description, image, link) VALUES
('TR3S Steakhouse', 'RESTAURANTE', 'Registro, SP', 'Especialista em cortes nobres e experiência gastronômica premium no coração do Vale.', 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=800', 'https://www.instagram.com/tr3ssteakhouse/'),
('Parada Oriental', 'RESTAURANTE', 'Registro, SP', 'O mais tradicional restaurante de culinária japonesa e chinesa da região.', 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&q=80&w=800', 'https://www.instagram.com/paradaoriental/'),
('Lito Palace Hotel', 'HOTEL', 'Registro, SP', 'Hospedagem clássica com conforto e localização privilegiada para negócios ou lazer.', 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=80&w=800', 'http://www.litopalace.com.br/'),
('Recanto dos Golfinhos', 'RESTAURANTE', 'Cananéia, SP', 'Frutos do mar frescos com vista para o mar pequeno. Famoso pelas ostras gratinadas.', 'https://images.unsplash.com/photo-1551731144-ad07aa297c3c?auto=format&fit=crop&q=80&w=800', '#'),
('Hotel Marazul', 'HOTEL', 'Cananéia, SP', 'Estrutura completa com lazer, piscinas e o melhor café da manhã caiçara.', 'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&q=80&w=800', 'https://www.hotelmarazul.com.br/'),
('Restaurante Panela Velha', 'RESTAURANTE', 'Iguape, SP', 'Comida caseira e frutos do mar em um ambiente histórico e acolhedor.', 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&q=80&w=800', '#'),
('Pousada Retiro das Caravelas', 'HOTEL', 'Cananéia, SP', 'Charme e tranquilidade em uma pousada rodeada pela Mata Atlântica.', 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&q=80&w=800', 'https://www.retirodascaravelas.com.br/'),
('Vila Verde Café e Bistrô', 'CAFÉ/BISTRÔ', 'Registro, SP', 'Espaço aconchegante para cafés especiais, tortas artesanais e almoços executivos.', 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&q=80&w=800', '#'),
('Pier Cozinha e Bar', 'RESTAURANTE', 'Iguape, SP', 'O ponto de encontro para drinks e o melhor peixe na brasa da orla de Iguape.', 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&q=80&w=800', '#'),
('Ilha do Cardoso', 'TURISMO', 'Cananéia, SP', 'Paraíso ecológico com trilhas, cachoeiras e praias desertas. Patrimônio da Humanidade.', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=800', '#'),
('Sítio Shimada - Chá da Obaatian', 'TURISMO', 'Registro, SP', 'Visita guiada pela história do chá no Brasil com degustação artesanal.', 'https://images.unsplash.com/photo-1544739313-6fad02872377?auto=format&fit=crop&q=80&w=800', 'https://www.chadaobaatian.com.br/'),
('Basílica Bom Jesus de Iguape', 'TURISMO', 'Iguape, SP', 'Centro de peregrinação e fé com arquitetura colonial deslumbrante.', 'https://images.unsplash.com/photo-1548544149-4835e62ee5b3?auto=format&fit=crop&q=80&w=800', '#'),
('Caverna do Diabo', 'TURISMO', 'Eldorado, SP', 'A maior caverna do estado de São Paulo, com formações rochosas espetaculares.', 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&q=80&w=800', '#'),
('Dunas do Araçá', 'TURISMO', 'Ilha Comprida, SP', 'Extensas dunas preservadas à beira-mar, ideais para contemplação da natureza.', 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&q=80&w=800', '#')
ON CONFLICT DO NOTHING;

-- Instituições (Restaurando as ausentes)
INSERT INTO instituicoes (name, city, address, phone, link, cover, type, description, history, presidents, services) VALUES
('OAB Registro', 'Registro', 'Rua Pres. Getúlio Vargas, 100 - Centro, Registro - SP', '(13) 3821-2345', 'https://oabregistro.org.br', 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=1200', 'OAB - 175ª Subseção', 'A 175ª Subseção da OAB - Registro atua na defesa das prerrogativas dos advogados...', 'A OAB Registro tem sido um pilar da advocacia no Vale do Ribeira...', '[{"name": "Diretoria Atual", "period": "2025-2027"}]', '["Assistência Judiciária", "Comissão de Ética", "ESA", "Certificação Digital"]'),
('OAB Iguape', 'Iguape', 'Rua das Almas, 50 - Centro, Iguape - SP', '(13) 3841-1234', '#', 'https://images.unsplash.com/photo-1505664194779-8beaceb93744?auto=format&fit=crop&q=80&w=1200', 'OAB - 195ª Subseção', 'Subseção histórica da OAB, atendendo a advocacia do litoral sul e Ilha Comprida.', 'A OAB Iguape (195ª Subseção) tem um papel fundamental na mediação de demandas locais.', '[{"name": "Nova Diretoria", "period": "2025-2027"}]', '["Apoio ao Advogado", "Sala dos Advogados (Fórum)"]'),
('OAB Jacupiranga', 'Jacupiranga', 'Av. Hilda, 200 - Centro, Jacupiranga - SP', '(13) 3864-5678', '#', 'https://images.unsplash.com/photo-1436450412740-6b988f486c6b?auto=format&fit=crop&q=80&w=1200', 'OAB - 192ª Subseção', 'Serve aos advogados de Jacupiranga, Pariquera-Açu, Cananéia, Eldorado, Cajati e Barra do Turvo.', 'A OAB Jacupiranga completou 30 anos em 2022. Recentemente elegeu sua primeira presidente mulher.', '[{"name": "Dra. Caroline Alves Salvador", "period": "2025-2027"}]', '["Assistência Judiciária Gratuita", "Núcleo da ESA"]'),
('Faculdade de Direito (UNIVR)', 'Registro', 'Rodovia Régis Bittencourt, Km 442', '(13) 3828-1000', 'https://unisepe.com.br', 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=1200', 'FACULDADE', 'A principal instituição de ensino jurídico da região, parte do grupo UNISEPE.', 'O curso de Direito foi criado para atender a demanda regional, formando juristas comprometidos.', '[{"name": "Reitoria UNISEPE", "period": "Atual"}]', '["Graduação em Direito", "NPJ", "Biblioteca"]');

-- Vagas (Fevereiro 2026 - Resgatadas)
INSERT INTO vagas (title, company, location, description, link) VALUES
('Professor Substituto - Recursos Pesqueiros', 'UNESP Registro', 'Registro, SP', 'Processo seletivo para docente na área de Engenharia de Pesca. Inscrições até 18/02/2026.', 'https://www.unesp.br'),
('Motorista Operacional', 'Sabesp', 'Jacupiranga, SP', 'Condução de veículos para transporte de pessoas e equipamentos. Requisito CNH C ou D.', 'https://www.sabesp.com.br'),
('Mestre de Obras / Infraestrutura', 'Privada', 'Registro, SP', 'Supervisão de canteiros de obras no Vale do Ribeira. Necessário experiência comprovada.', 'https://www.indeed.com'),
('Assistente de Logística no Agronegócio', 'Cooperativa Vale', 'Jacupiranga, SP', 'Suporte em operações logísticas e controle de estoque de insumos agrícolas.', 'https://www.cathoo.com.br');

-- Concursos (Fevereiro 2026)
INSERT INTO concursos (entidade, cargo, vagas, remuneracao, status, nivel, link) VALUES
('Prefeitura de Iguape', 'Diversos Cargos Nível Superior', '25 + CR', 'Até R$ 8.288,27', 'Inscrições até 09/02', 'MUNICIPAL', 'https://www.iguape.sp.gov.br'),
('Câmara Municipal de Itariri', 'Cargos Administrativos', 'CR', 'Consultar Edital', 'Prova em 22/02', 'MUNICIPAL', 'https://www.itariri.sp.leg.br');

-- Voz do Vale (Restaurando Artigos)
INSERT INTO voz_do_vale (title, author, type, institution, year, resume, content, image, isFeatured, tags) VALUES
('Multiparentalidade e seus Efeitos Sucessórios', 'Dr. André Santos', 'ARTIGO CIENTÍFICO', 'OAB Registro', '2026', 'Um estudo profundo sobre as novas configurações familiares e direitos sucessórios.', 'O reconhecimento da multiparentalidade pelo STF...', 'https://placehold.co/800x400/1a1a1a/ffffff?text=Sucessões', false, '["Direito de Família", "STF"]'),
('Impactos da Regularização Fundiária Rural', 'Dr. Carlos Mendes', 'TCC/TESE', 'UNISEPE', '2024', 'Como a titulação de terras em Jacupiranga influenciou o crédito agrícola.', 'Estudo de caso focado no agronegócio regional...', '', false, '["Direito Agrário", "Vale do Ribeira"]');

-- Voz do Vale
INSERT INTO voz_do_vale (title, author, type, institution, year, resume, content, image, link, "isFeatured") VALUES
('Vade Mecum 2026: Por que o Rideel continua sendo minha escolha?', 'Rafael Suyama', 'RESENHA', 'Análise Editorial', '2026', 'A virada de ano no Direito traz sempre aquela dúvida clássica...', '<h3>O Campeão de Bancada: Rideel Acadêmico (42ª Ed.)</h3>...', 'https://placehold.co/400x600/1a1a1a/ffffff?text=Vade+Mecum+2026', 'https://www.amazon.com.br', true),
('A Constitucionalidade das Leis Municipais no Vale do Ribeira', 'Dra. Ana Paula Souza', 'ARTIGO CIENTÍFICO', 'UNISEPE - Registro', '2025', 'Análise sobre a competência legislativa...', '', '', '#', false)
ON CONFLICT DO NOTHING;

-- 4. SEGURANÇA (RLS)
ALTER TABLE config ENABLE ROW LEVEL SECURITY;
ALTER TABLE news ENABLE ROW LEVEL SECURITY;
ALTER TABLE eventos ENABLE ROW LEVEL SECURITY;
ALTER TABLE editors ENABLE ROW LEVEL SECURITY;
ALTER TABLE leituras ENABLE ROW LEVEL SECURITY;
ALTER TABLE concursos ENABLE ROW LEVEL SECURITY;
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE instituicoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE equipamentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE voz_do_vale ENABLE ROW LEVEL SECURITY;
ALTER TABLE reservas ENABLE ROW LEVEL SECURITY;
ALTER TABLE vagas ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
    t text;
BEGIN
    FOR t IN SELECT table_name FROM information_schema.tables 
             WHERE table_schema = 'public' 
             AND table_name IN ('config', 'news', 'eventos', 'editors', 'leituras', 'concursos', 'contacts', 'instituicoes', 'equipamentos', 'comments', 'voz_do_vale', 'reservas', 'vagas')
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I', 'Public_Read_' || t, t);
        EXECUTE format('CREATE POLICY %I ON %I FOR SELECT USING (true)', 'Public_Read_' || t, t);
        
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I', 'Public_Write_' || t, t);
        EXECUTE format('CREATE POLICY %I ON %I FOR ALL USING (true) WITH CHECK (true)', 'Public_Write_' || t, t);
    END LOOP;
END $$;
