-- Create tables for Hermeneuta Content Management

-- News Table
CREATE TABLE IF NOT EXISTS news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT DEFAULT 'Geral',
  content TEXT NOT NULL,
  citation TEXT,
  author TEXT,
  author_id TEXT,
  image TEXT,
  date TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Events Table
CREATE TABLE IF NOT EXISTS eventos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  location TEXT,
  description TEXT,
  type TEXT DEFAULT 'PRESENCIAL',
  link TEXT,
  image TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Editors Table
CREATE TABLE IF NOT EXISTS editors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT,
  bio TEXT,
  avatar TEXT,
  username TEXT UNIQUE,
  password TEXT, -- In a real prod app, hash this! For detailed mocks, text is fine.
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Leituras (Reading Suggestions) Table
CREATE TABLE IF NOT EXISTS leituras (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT,
  type TEXT DEFAULT 'LIVRO',
  category TEXT,
  synopsis TEXT,
  cover TEXT,
  link TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Concursos (Public Exams) Table
CREATE TABLE IF NOT EXISTS concursos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entidade TEXT NOT NULL,
  cargo TEXT NOT NULL,
  vagas TEXT,
  remuneracao TEXT,
  status TEXT DEFAULT 'Inscrições Abertas',
  nivel TEXT DEFAULT 'MUNICIPAL',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Contacts Table
CREATE TABLE IF NOT EXISTS contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  comarca TEXT,
  setor TEXT,
  telefone TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) - Optional for now, ensures data safety later
ALTER TABLE news ENABLE ROW LEVEL SECURITY;
ALTER TABLE eventos ENABLE ROW LEVEL SECURITY;
ALTER TABLE editors ENABLE ROW LEVEL SECURITY;
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- Policy to allow public read access
CREATE POLICY "Public Read News" ON news FOR SELECT USING (true);
CREATE POLICY "Public Read Events" ON eventos FOR SELECT USING (true);
CREATE POLICY "Public Read Editors" ON editors FOR SELECT USING (true);
CREATE POLICY "Public Read Contacts" ON contacts FOR SELECT USING (true);

-- Policy to allow authenticated (or public for now since we manage via admin panel) insert/update
-- Ideally locking this down to admin users only in the future
CREATE POLICY "Public Insert News" ON news FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update News" ON news FOR UPDATE USING (true);
CREATE POLICY "Public Delete News" ON news FOR DELETE USING (true);

CREATE POLICY "Public Insert Events" ON eventos FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Events" ON eventos FOR UPDATE USING (true);
CREATE POLICY "Public Delete Events" ON eventos FOR DELETE USING (true);

CREATE POLICY "Public Insert Editors" ON editors FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Editors" ON editors FOR UPDATE USING (true);
CREATE POLICY "Public Delete Editors" ON editors FOR DELETE USING (true);

CREATE POLICY "Public Insert Contacts" ON contacts FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Contacts" ON contacts FOR UPDATE USING (true);
CREATE POLICY "Public Delete Contacts" ON contacts FOR DELETE USING (true);

-- Enable RLS for leituras and concursos
ALTER TABLE leituras ENABLE ROW LEVEL SECURITY;
ALTER TABLE concursos ENABLE ROW LEVEL SECURITY;

-- Policies for leituras
CREATE POLICY "Public Read Leituras" ON leituras FOR SELECT USING (true);
CREATE POLICY "Public Insert Leituras" ON leituras FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Leituras" ON leituras FOR UPDATE USING (true);
CREATE POLICY "Public Delete Leituras" ON leituras FOR DELETE USING (true);

-- Policies for concursos
CREATE POLICY "Public Read Concursos" ON concursos FOR SELECT USING (true);
CREATE POLICY "Public Insert Concursos" ON concursos FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Concursos" ON concursos FOR UPDATE USING (true);
CREATE POLICY "Public Delete Concursos" ON concursos FOR DELETE USING (true);
