-- SQL Update Script: Viva Hermeneuta!
-- This script adds the missing tables and security policies for the new sections.

-- 1. Vagas Table (Vagas de Emprego)
CREATE TABLE IF NOT EXISTS vagas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  company TEXT,
  location TEXT,
  description TEXT,
  link TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Reservas Table (Guia Regional)
CREATE TABLE IF NOT EXISTS reservas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT DEFAULT 'OUTROS',
  location TEXT,
  description TEXT,
  image TEXT,
  link TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Voz do Vale (Academic) Table
CREATE TABLE IF NOT EXISTS voz_do_vale (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT,
  author_id TEXT,
  type TEXT DEFAULT 'ARTIGO CIENTÍFICO',
  institution TEXT,
  year TEXT,
  resume TEXT,
  content TEXT,
  image TEXT,
  link TEXT,
  isFeatured BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Config Table (Maintenance etc)
CREATE TABLE IF NOT EXISTS config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Enable Row Level Security (RLS)
ALTER TABLE vagas ENABLE ROW LEVEL SECURITY;
ALTER TABLE reservas ENABLE ROW LEVEL SECURITY;
ALTER TABLE voz_do_vale ENABLE ROW LEVEL SECURITY;
ALTER TABLE config ENABLE ROW LEVEL SECURITY;

-- 6. Drop existing policies to avoid conflicts
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Public Read Vagas" ON vagas;
    DROP POLICY IF EXISTS "Public Write Vagas" ON vagas;
    DROP POLICY IF EXISTS "Public Read Reservas" ON reservas;
    DROP POLICY IF EXISTS "Public Write Reservas" ON reservas;
    DROP POLICY IF EXISTS "Public Read Voz do Vale" ON voz_do_vale;
    DROP POLICY IF EXISTS "Public Write Voz do Vale" ON voz_do_vale;
    DROP POLICY IF EXISTS "Public Read Config" ON config;
    DROP POLICY IF EXISTS "Public Write Config" ON config;
END $$;

-- 7. Create Read Policies
CREATE POLICY "Public Read Vagas" ON vagas FOR SELECT USING (true);
CREATE POLICY "Public Read Reservas" ON reservas FOR SELECT USING (true);
CREATE POLICY "Public Read Voz do Vale" ON voz_do_vale FOR SELECT USING### Reservas Section Refinement

#### [MODIFY] [ReservasFeed.jsx](file:///c:/Users/Usuario/OneDrive/Área de Trabalho/site/src/components/ReservasFeed.jsx)
- Implement `selectedCity` state.
- Extract unique cities from `reservas` data for the filter UI.
- Update filtering logic to account for cities.
- Refactor JSX to support a **List View** (horizontal cards).
- Move `styled jsx` to `index.css`.

#### [MODIFY] [index.css](file:///c:/Users/Usuario/OneDrive/Área de Trabalho/site/src/index.css)
- Add specialized list-row styles for Reservas items.
- Ensure responsive behavior (stack on mobile).
- Style the new City Filter tabs.

## Verification Plan

### Manual Verification
- Verify that clicking a city filter only shows relevant results.
- Confirm the guide displays as a list of horizontal items.
- Check mobile responsiveness.
 FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public Write Config" ON config FOR ALL USING (true) WITH CHECK (true);

-- 9. Initial Config
INSERT INTO config (key, value) VALUES ('maintenance_mode', 'false') ON CONFLICT (key) DO NOTHING;
